# ローカルディレクトリ名  Git リポジトリ URL  ブランチ名
auth     git@github.com:waddle-inc/auth.git     main
ifukuya  git@github.com:waddle-inc/ifukuya.git  main
tools    git@github.com:waddle-inc/tools.git    main
corp     git@github.com:waddle-inc/corp.git     main
